---
title: 'Preprocessing moral dilemmas pilot'
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../helpers.R")
```


```{r}
read.pcibex <- function(filepath, auto.colnames=TRUE, fun.col=function(col,cols){cols[cols==col]<-paste(col,"Ibex",sep=".");return(cols)}) {
  n.cols <- max(count.fields(filepath,sep=",",quote=NULL),na.rm=TRUE)
  if (auto.colnames){
    cols <- c()
    con <- file(filepath, "r")
    while ( TRUE ) {
      line <- readLines(con, n = 1, warn=FALSE)
      if ( length(line) == 0) {
        break
      }
      m <- regmatches(line,regexec("^# (\\d+)\\. (.+)\\.$",line))[[1]]
      if (length(m) == 3) {
        index <- as.numeric(m[2])
        value <- m[3]
        if (is.function(fun.col)){
         cols <- fun.col(value,cols)
        }
        cols[index] <- value
        if (index == n.cols){
          break
        }
      }
    }
    close(con)
    return(read.csv(filepath, comment.char="#", header=FALSE, col.names=cols))
  }
  else{
    return(read.csv(filepath, comment.char="#", header=FALSE, col.names=seq(1:n.cols)))
  }
}

# Read in the results
d <- read.pcibex("../data/results_prod.csv")


names(d)
nrow(d)
length(unique(d$MD5.hash.of.participant.s.IP.address))
```


```{r}
# Assign participant number
d$Participant <- as.integer(factor(d$MD5.hash.of.participant.s.IP.address))
length(unique(d$Participant))

# Separate out demographic information
demo <- d %>% 
    filter((Label == "demo") &
             (!Parameter %in% c("_Trial_","_Header_"))) %>% 
    select(Participant,Parameter,Value) %>% 
    pivot_wider(
        names_from = Parameter,
        values_from = Value,
        names_prefix = "Demo_"
      )

d.sub <- d %>% 
    filter(Label %in% c("practice","test_phase1","fillers","test_phase2") &
             (PennElementType == "Scale")) %>% 
    select(Participant,Label,PennElementName,Value,TrialType,Group,Number,Valence) %>% 
    pivot_wider(
      names_from = PennElementName,
      values_from = Value
    )


df_combined <- full_join(demo, d.sub, by = "Participant")

# Collapse List-columns, 
# convert c(3, 4, 5) to "3;4;5"
df_combined <- df_combined |>
  dplyr::mutate(across(where(is.list),
                       ~ sapply(., paste, collapse = ";")))


table(df_combined$R1A)
```

# Convert each scale into an ordered factor
```{r}
# Define the correct order of your responses
# Convert responses to ordered factors

df_combined$R1A <- factor(
  df_combined$R1A,
  levels = c("Very wrong",
             "Wrong",
             "Somewhat wrong",
             "Somewhat right",
             "Right",
             "Very right"),
  ordered = TRUE
)

df_combined$R2 <- factor(
  df_combined$R2,
  levels = c("Definitely no correct answer",
             "Probably no correct answer",
             "Maybe no correct answer",
             "Maybe there is a correct answer",
             "Probably there is a correct answer",
             "Definitely there is a correct answer"),
  ordered = TRUE
)

df_combined$R3 <- factor(
  df_combined$R3,
  levels = c("Almost everyone would agree with me",
             "Most of them would agree with me",
             "Some of them would agree with me",
             "Some of them would disagree with me",
             "Most of them would disagree with me",
             "Almost everyone would disagree with me"),
  ordered = TRUE
)

df_combined$R4 <- factor(
  df_combined$R4,
  levels = c("Very easy",
             "Somewhat easy",
             "A little easy",
             "A little difficult",
             "Somewhat difficult",
             "Very difficult"),
  ordered = TRUE
)

df_combined$R5 <- factor(
  df_combined$R5,
  levels = c("Neither of us needs to be mistaken",
             "Probably neither of us needs to be mistaken",
             "Maybe neither of us needs to be mistaken",
             "The other person is maybe mistaken",
             "The other person is likely mistaken",
             "The other person is clearly mistaken"),
  ordered = TRUE
)

df_combined$R6 <- factor(
  df_combined$R6,
  levels = c("Extremely uncomfortable",
             "Very uncomfortable",
             "Mildly uncomfortable",
             "Mildly comfortable",
             "Very comfortable",
             "Extremely comfortable"),
  ordered = TRUE
)

```


```{r}

# Write to .csv not aggregating over participants
write.csv(df_combined,"../data/processed.csv")

```
